### ISSUE TITLE
Number of overall violations divided by number of columns in `are_complete`

### ISSUE THREAD

**Issue by GeorgelPreput** [canimus/cuallee#110]
**Describe the bug**
The issue is probably noticeable with other `are_*` validations. It seems that when passing a number of columns to be checked, the total number of violations found will be divided by the number of columns given. For example, if a check will be done over 3 columns, and 12 violations are found, only 4 will be reported. This is OK if all violations were on the same row, but will underreport when the violations are on different rows.

**To Reproduce**
Run the following code:
```python
from pyspark.sql import SparkSession
from cuallee import Check, CheckLevel
```
```python
spark = SparkSession.builder.getOrCreate()

check = Check(CheckLevel.WARNING, "Not NULL").are_complete(["col_a", "col_b", "col_c"])
```
```python
# This is fine

df1 = spark.createDataFrame([
    {"col_a": 1, "col_b": 1, "col_c": 1}, {"col_a": 2, "col_b": 2, "col_c": 2}, {"col_a": 3, "col_b": 3, "col_c": 3}
], schema="struct<col_a: int, col_b: int, col_c: int>")
df1.show(truncate=False)
check.validate(df1).show(truncate=False)
```
>```
>+-----+-----+-----+
>|col_a|col_b|col_c|
>+-----+-----+-----+
>|1    |1    |1    |
>|2    |2    |2    |
>|3    |3    |3    |
>+-----+-----+-----+
>
>+---+-------------------+--------+-------+---------------------------+------------+-----+----+----------+---------+--------------+------+
>|id |timestamp          |check   |level  |column                     |rule        |value|rows|violations|pass_rate|pass_threshold|status|
>+---+-------------------+--------+-------+---------------------------+------------+-----+----+----------+---------+--------------+------+
>|1  |2023-08-07 12:23:32|Not NULL|WARNING|('col_a', 'col_b', 'col_c')|are_complete|N/A  |3   |0.0       |1.0      |1.0           |PASS  |
>+---+-------------------+--------+-------+---------------------------+------------+-----+----+----------+---------+--------------+------+
>```
```python
# This is also fine

df2 = spark.createDataFrame([
    {"col_a": None, "col_b": None, "col_c": None}, {"col_a": 2, "col_b": 2, "col_c": 2}, {"col_a": 3, "col_b": 3, "col_c": 3}
], schema="struct<col_a: int, col_b: int, col_c: int>")
df2.show(truncate=False)
check.validate(df2).show(truncate=False)
```
>```
>+-----+-----+-----+
>|col_a|col_b|col_c|
>+-----+-----+-----+
>|null |null |null |
>|2    |2    |2    |
>|3    |3    |3    |
>+-----+-----+-----+
>
>+---+-------------------+--------+-------+---------------------------+------------+-----+----+----------+------------------+--------------+------+
>|id |timestamp          |check   |level  |column                     |rule        |value|rows|violations|pass_rate         |pass_threshold|status|
>+---+-------------------+--------+-------+---------------------------+------------+-----+----+----------+------------------+--------------+------+
>|1  |2023-08-07 12:23:32|Not NULL|WARNING|('col_a', 'col_b', 'col_c')|are_complete|N/A  |3   |1.0       |0.6666666666666666|1.0           |FAIL  |
>+---+-------------------+--------+-------+---------------------------+------------+-----+----+----------+------------------+--------------+------+
>```
```python
# This should show 3 violations, but it seems that the number of violations outputted is divided by the number of columns

df3 = spark.createDataFrame([
    {"col_a": None, "col_b": 1, "col_c": 1}, {"col_a": None, "col_b": 2, "col_c": 2}, {"col_a": None, "col_b": 3, "col_c": 3}
], schema="struct<col_a: int, col_b: int, col_c: int>")
df3.show(truncate=False)
check.validate(df3).show(truncate=False)
```
>```
>+-----+-----+-----+
>|col_a|col_b|col_c|
>+-----+-----+-----+
>|null |1    |1    |
>|null |2    |2    |
>|null |3    |3    |
>+-----+-----+-----+
>
>+---+-------------------+--------+-------+---------------------------+------------+-----+----+----------+------------------+--------------+------+
>|id |timestamp          |check   |level  |column                     |rule        |value|rows|violations|pass_rate         |pass_threshold|status|
>+---+-------------------+--------+-------+---------------------------+------------+-----+----+----------+------------------+--------------+------+
>|1  |2023-08-07 12:23:32|Not NULL|WARNING|('col_a', 'col_b', 'col_c')|are_complete|N/A  |3   |1.0       |0.6666666666666666|1.0           |FAIL  |
>+---+-------------------+--------+-------+---------------------------+------------+-----+----+----------+------------------+--------------+------+
>```
```python
# This should also show 3 violations and a 0% pass rate

df4 = spark.createDataFrame([
    {"col_a": None, "col_b": 1, "col_c": 1}, {"col_a": 2, "col_b": None, "col_c": 2}, {"col_a": 3, "col_b": 3, "col_c": None}
], schema="struct<col_a: int, col_b: int, col_c: int>")
df4.show(truncate=False)
check.validate(df4).show(truncate=False)
```
>```
>+-----+-----+-----+
>|col_a|col_b|col_c|
>+-----+-----+-----+
>|null |1    |1    |
>|2    |null |2    |
>|3    |3    |null |
>+-----+-----+-----+
>
>+---+-------------------+--------+-------+---------------------------+------------+-----+----+----------+------------------+--------------+------+
>|id |timestamp          |check   |level  |column                     |rule        |value|rows|violations|pass_rate         |pass_threshold|status|
>+---+-------------------+--------+-------+---------------------------+------------+-----+----+----------+------------------+--------------+------+
>|1  |2023-08-07 12:23:32|Not NULL|WARNING|('col_a', 'col_b', 'col_c')|are_complete|N/A  |3   |1.0       |0.6666666666666666|1.0           |FAIL  |
>+---+-------------------+--------+-------+---------------------------+------------+-----+----+----------+------------------+--------------+------+
>```

**Expected behavior**
Ideally, the number of violations should reflect the number of offending rows (unless I'm misunderstanding something).

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Visual Studio Code / Jupyter Notebooks
 - Version `cuallee==0.4.7`

**Comment by canimus** [comment]
fixed #112
