### ISSUE TITLE
Executing validation tasks through Spark Connect is failing

### ISSUE THREAD

**Issue by dsaad68** [canimus/cuallee#184]
## Issue
I've been using Spark Connect for both testing and data validation tasks. Despite following the provided documentation closely, I encountered errors with every example I attempted. 

These issues occurred on Apache Spark version `3.5.1`. Below, I provide detailed steps to reproduce two specific errors, along with the corresponding error messages.

Environment:

- Python Version: `3.11.8`
- Apache Spark Versions Tested:  `3.5.1`
- Scala Version: `2.12`
- Operating System: Windows

### Setup

1. Single node Spark cluster initiated via Docker using the command:
```sh
docker run -ti --name spark -p 15002:15002 bitnami/spark:latest /opt/bitnami/spark/sbin/start-connect-server.sh --packages org.apache.spark:spark-connect_2.12:3.5.1
```

2. Spark Session creation:
```python
spark = SparkSession.builder.appName("PySpark Test") \
            .remote("sc://localhost:15002") \
            .getOrCreate()
```

### 1. Error with Dates Example

**Issue Reproduction:**

Executing the Dates Example as provided in the documentation:
```python
# Unique values on id
check = Check(CheckLevel.WARNING, "CheckIsBetweenDates")
df = spark.sql(
    """
    SELECT 
        explode(
            sequence(
                to_date('2022-01-01'), 
                to_date('2022-01-10'), 
                interval 1 day)) as date
    """)
assert (
    check.is_between("date", "2022-01-01", "2022-01-10")
    .validate(df)
    .first()
    .status == "PASS"
)
```

**Error Message:**
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[8], line 14
      3 df = spark.sql(
      4     """
      5     SELECT 
   (...)
     10                 interval 1 day)) as date
     11     """)
     12 df = df.toPandas()
     13 assert (
---> 14     check.is_between("date", "2022-01-01", "2022-01-10")
     15     .validate(df)
     16     .first()
     17     .status == "PASS"
     18 )

File c:\Users\Dsaad\GitHub\pyspark-tools\.venv\Lib\site-packages\cuallee\__init__.py:403, in Check.is_between(self, column, value, pct)
    401 def is_between(self, column: str, value: Tuple[Any], pct: float = 1.0):
    402     """Validation of a column between a range"""
--> 403     Rule("is_between", column, value, CheckDataType.AGNOSTIC, pct) >> self._rule
    404     return self

File <string>:13, in __init__(self, method, column, value, data_type, coverage, options, status, violations, pass_rate, ordinal)

File c:\Users\Dsaad\GitHub\pyspark-tools\.venv\Lib\site-packages\cuallee\__init__.py:100, in Rule.__post_init__(self)
     99 def __post_init__(self):
--> 100     if (self.coverage <= 0) or (self.coverage > 1):
    101         raise ValueError("Coverage should be between 0 and 1")
    103     if isinstance(self.column, List):

TypeError: '<=' not supported between instances of 'str' and 'int'
```

### 2. Error with Completeness Check Example:

**Issue Reproduction:**

Executing an example that checks for null values and uniqueness:
```python

from datetime import date
from pyspark.sql import Row

df = spark.createDataFrame([
        Row(user_id=1111, order_id=4343, preferred_store='string1', birthdate=date(1999, 1, 1), joined_date=date(2022, 6, 1)),
        Row(user_id=2222, order_id=5454, preferred_store='string2', birthdate=date(2000, 2, 1), joined_date=date(2022, 7, 2)),
        Row(user_id=3333, order_id=6565, preferred_store='string3', birthdate=date(2001, 3, 1), joined_date=date(2022, 8, 3))
        ])

# Nulls on column Id
check = Check(CheckLevel.WARNING, "Completeness")
(   check
    .is_complete("user_id")
    .is_unique("user_id")
    .validate(df)
).show()
```

**Error Message:**

```
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
Cell In[7], line 13
      7 # Nulls on column Id
      8 check = Check(CheckLevel.WARNING, "Completeness")
      9 (   check
     10     .is_complete("user_id")
     11     .is_unique("user_id")
---> 12     .validate(df)
     13 ).show()

File c:\Users\Dsaad\GitHub\pyspark-tools\.venv\Lib\site-packages\cuallee\__init__.py:703, in Check.validate(self, dataframe)
    700     self.compute_engine = importlib.import_module("cuallee.polars_validation")
    702 else:
--> 703     raise Exception(
    704         "Cuallee is not ready for this data structure. You can log a Feature Request in Github."
    705     )
    707 assert self.compute_engine.validate_data_types(
    708     self.rules, dataframe
    709 ), "Invalid data types between rules and dataframe"
    711 return self.compute_engine.summary(self, dataframe)

Exception: Cuallee is not ready for this data structure. You can log a Feature Request in Github.
```

I would appreciate any guidance or updates on resolving these errors. Thank you for your assistance.

**Comment by dsaad68** [comment]
I have investigated the issue in more depth:

* DataFrames generated via Spark Connect are of the `pyspark.sql.connect.dataframe.DataFrame` type. Unfortunately, this type is not compatible with the `validate` function located in `__init__.py`. Which can be remedied, for example:
```python 

try:
    from pyspark.sql.connect.dataframe import DataFrame as pyspark_connect_dataframe
except (ModuleNotFoundError, ImportError):
    logger.debug("KO: PySpark Connect")

def validate(self, dataframe: Any):
        ...
        # When dataframe is Spark Connect DataFrame API
        elif "pyspark_connect_dataframe" in globals() and isinstance(
            dataframe, pyspark_connect_dataframe
        ):
            self.compute_engine = importlib.import_module("cuallee.pyspark_validation
        ...
```
* Additionally, the `summary` function in `pyspark_validation.py` lacks the functionality to accept parameters necessary for initiating a Remote Spark Session, essential for Spark Connect. 
A **workaround** for this issue involves setting one environment variable as follows in the code:
  ```python
  os.environ['SPARK_REMOTE'] = "sc://localhost:15002"
  ```
* Currently, as of its latest version 3.5.1, Spark Connect does not support the `Observation` feature, which is crucial to this library's functionality.
  ```
  raise PySparkNotImplementedError(
  pyspark.errors.exceptions.base.PySparkNotImplementedError: [NOT_IMPLEMENTED] Observation support for Spark Connect is not implemented.
  ```

It's unfortunate, as I was eager to integrate the `cuallee` package into my PySpark process. I'll keep an eye on subsequent releases of PySpark, and if they start supporting `Observation` with Spark Connect, I will submit a detailed proposal or contribute via a pull request.

**Comment by canimus** [comment]
Thank you @dsaad68 for investigating the use of `cuallee` in the context of Spark Connect. To be honest, the fix does not look that complex. The `pyspark_validation.py` already takes in consideration versions earlier of `3.3.0` that don't have support for `Observation` and it falls back to use a plain `SELECT` to compute the quality metrics. We will explore the feature of searching for a Spark Connect session in the `globals` as we do for compatibility with Databricks, and follow your advise on the use of a `ENV=CUALLEE_SPARK_REMOTE` to retrieve the location of the endpoint as a fallback. Thanks for the very detailed root cause analysis, very much appreciated.

**Comment by canimus** [comment]
Solved with #185

**Comment by dsaad68** [comment]
Thanks a lot. It was quick.
I finished my fix, but you beat me to it. 

Just one suggestion, if `os.environ[SPARK_CONNECT_MODE_ENABLED] == "1"`  that means the spark session is connected with spark connect. It is a good identifier that Spark Connect is being used.

**Comment by canimus** [comment]
Hi @dsaad68 , bring your implementation in, if you feel it fits more your use case. Always happy to see new contributions, and let me know if the `v0.9.1` worked out. The fact that you investigated all the way, made the rest of the spark-connect part relatively trivial. The real value was understanding the session creation and the observation limitation you highlighted. So again, thanks again for pointing out that.
