### ISSUE TITLE
[JOSS Review] Show documentation page prominently

### ISSUE THREAD

**Issue by FlorianK13** [canimus/cuallee#226]
Great that you have updated your documentation page. Could you now refer to it prominently, for example in the Readme and/or in the project description on github (upper right corner of the github repository page).

**Comment by canimus** [comment]
Hi @FlorianK13 reference already exists in README.md in the section: [Documentation](https://github.com/canimus/cuallee?tab=readme-ov-file#documentation)

**Comment by canimus** [comment]
Thanks for the suggestion @FlorianK13 . Find out that you can add a website in the Settings of the project. Now docs, also appear as a direct link of the project.

**Comment by canimus** [comment]
@FlorianK13 do you consider this one as completed?

**Comment by FlorianK13** [comment]
Yes, sure. Then I will close issues when I think they are completed?
