### ISSUE TITLE
[JOSS Review] Performance Tests

### ISSUE THREAD

**Issue by FlorianK13** [canimus/cuallee#227]
For the joss review, I need to validate the performance test:
```Performance: If there are any performance claims of the software, have they been confirmed? (If there are no claims, please check off this item.)```
Is the `temp/taxi/` parquet files open data? If yes, could you provide them somehow?

**Comment by canimus** [comment]
Hi @FlorianK13 yes it is open and available here:
Yes its open data here:
https://www.nyc.gov/site/tlc/about/tlc-trip-record-data.page
Under the accordion sections of the site, with the data per year.

```bash
wget https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2024-01.parquet
wget https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2024-02.parquet
```

**Comment by FlorianK13** [comment]
For me the difference was not as big as in the Readme (more like cuallee 1:10min and pydeequ 1:40min using the sparker.py script in the test/performance folders) - however these performance tests are probably hardware dependant. I could reproduce that cuallee is faster, so I guess that is all that matters.
