### ISSUE TITLE
[JOSS Review] `Paper` Report on state of the field

### ISSUE THREAD

**Issue by FlorianK13** [canimus/cuallee#228]
JOSS wants the software papers to contain a comparison to the state of the field, i.e.

```State of the field: Do the authors describe how this software compares to other commonly-used packages?```

Hence, could you add a section in your paper where you shortly compare `cuallee` to other data testing frameworks, like soda, great_expectations, or others?

This issue is part of a [JOSS Review](https://github.com/openjournals/joss-reviews/issues/6684)

**Comment by canimus** [comment]
Thank you @FlorianK13 we will include an additional section that address this request. Would you advise that we can then dismiss the word count limit of the paper?

**Comment by FlorianK13** [comment]
I don't know, maybe you can ask the editor in the Review Issue from JOSS?

**Comment by canimus** [comment]
Fixed by #235
