### ISSUE TITLE
[JOSS REVIEW] Great Expectations and Soda Core references are not rendering properly

### ISSUE THREAD

**Issue by devarops** [canimus/cuallee#245]
We see that in the article, we are trying to cite Soda Core and Great Expectations:

https://github.com/canimus/cuallee/blob/e4c12429c5f440d3b2f4a64417ef7cc2737e0842/paper/paper.md?plain=1#L58 

but it is not rendering properly:

![image](https://github.com/canimus/cuallee/assets/3461018/74d56af3-f65c-40a0-bf44-146df67539d8)

Maybe the `@software` option is not working.

https://github.com/canimus/cuallee/blob/e4c12429c5f440d3b2f4a64417ef7cc2737e0842/paper/paper.bib#L141-L152

We are confident that you can find a solution. Could you please consider using the `@misc` option or any other alternative that you think might work?

---

This issue is part of a [JOSS REVIEW](https://github.com/openjournals/joss-reviews/issues/6684)

**Comment by vestalisvirginis** [comment]
Thank you for your comment. But I don't understand what do you mean by 'it is not rendering properly' ? When running the pipeline to generate the manuscript, here is what we obtained:
- reference in the text:
<img width="743" alt="Screenshot 2024-05-30 at 08 13 44" src="https://github.com/canimus/cuallee/assets/54766741/0b29c1ce-9978-4b73-bb4c-70111c8d9298">
- in the bibliography:
<img width="811" alt="Screenshot 2024-05-30 at 08 14 00" src="https://github.com/canimus/cuallee/assets/54766741/ae27cfc1-17c8-4a51-828d-ff08cc3766e3">

(See also paper.pdf in the paper directory in the repository)

which is different to the screen shot. Could it be that the paper hasn't been updated to the last version on your side?

**Comment by devarops** [comment]
Sorry for the confusion! 😅
I was not looking at the most recent version.
